# Build semgrep via docker.
# See also Dockerfile at the root of the project.

name: docker

on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # optional if don't need multi-arch build
      - uses: docker/setup-buildx-action@v3
      - run: make build-docker

  #TODO: use matrix instead of copy paste? or move to .jsonnet?
  build-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make build-docker-libs
  build-libs-ocaml5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make build-docker-libs-ocaml5
